#!/usr/bin/env python3
"""Check the firmware's pitch arithmetic against the companion's.

The companion decides the tuning and the firmware plays it, and the only thing
they share is the 17 bytes of the `P` frame. Nothing at runtime can tell you the
two implementations of "what pitch is this key" agree -- the app asks meantonal in
floating point, the firmware does int32 millicents on a Cortex-M4 -- so this
script closes that gap on the host:

  1. Extracts `div_round`, `pitch_for_xy` and `pitch_params_apply` VERBATIM from
     Core/Src/main.c, so what runs here is the firmware's code and not a
     paraphrase that can drift away from it.
  2. Compiles them with clang and runs them over every key of a four-board grid,
     across nine tunings and both layouts.
  3. Diffs that against the same table computed by the JS mirror in
     check-tuning.mjs, which that script in turn checks against meantonal.
  4. Separately asserts the headline compatibility claim: at the compiled-in
     defaults the new code is byte-identical to the 31-EDO step-lattice formula
     it replaced, so flashing this firmware cannot change how a board sounds
     until something pushes a `P` frame.

Run with `npm run check:firmware`. Needs clang and node; it writes only into a
temporary directory.
"""

from __future__ import annotations

import json
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
COMPANION = HERE.parent
MAIN_C = COMPANION.parent / "Core" / "Src" / "main.c"

# Fifths in millicents: 12, 19, 31, 41, 53-EDO, 12-TET again, 1/4-comma
# meantone, and both ends of the legal range.
FIFTHS = [700000, 694737, 696774, 702439, 701887, 700000, 696578, 685714, 720000]
# Bosanquet is the identity; Wicki-Hayden is w = x - 2y, h = -y.
LAYOUTS = [((1, 0, 0, 1), (23, 7)), ((1, -2, 0, -1), (29, 13))]
BOARDS = 4


def grab(src: str, sig: str, frm: int = 0) -> str:
    """The brace-balanced declaration starting at `sig`.

    A function ends at its closing brace; a typedef or an initialiser carries on
    to the semicolon after it (`} pitch_params_t;`), so which one this is has to
    be decided from the text rather than assumed.
    """
    i = src.index(sig, frm)
    k = src.index("{", i)
    depth = 0
    while True:
        if src[k] == "{":
            depth += 1
        elif src[k] == "}":
            depth -= 1
            if depth == 0:
                break
        k += 1
    needs_semicolon = src[i:k].lstrip().startswith(("typedef", "static volatile", "static const"))
    return src[i : (src.index(";", k) + 1) if needs_semicolon else (k + 1)]


def build_harness(src: str, led_pos: list[list[int]]) -> str:
    defines = "\n".join(
        l for l in src.splitlines() if re.match(r"#define (TUNE_|PITCH_MSG_LEN|MPE_BEND_)", l)
    )
    params = grab(src, "typedef struct {", src.index("int32_t fifth_milli") - 400)
    if "fifth_milli" not in params:
        sys.exit("could not locate pitch_params_t in main.c")
    decl = grab(src, "static volatile pitch_params_t pitch_params =")
    div_round = grab(src, "static int32_t div_round(int32_t num, int32_t den)")
    pitch = grab(src, "static uint8_t pitch_for_xy(int32_t x, int32_t y,")
    apply_fn = grab(src, "static uint8_t pitch_params_apply(const uint8_t *m)")

    pos = ",".join(f"{{{x},{y}}}" for x, y in led_pos)
    fifths = ",".join(str(f) for f in FIFTHS)
    mats = ",".join("{%d,%d,%d,%d}" % m for m, _ in LAYOUTS)
    anch = ",".join("{%d,%d}" % a for _, a in LAYOUTS)

    return f"""/* GENERATED by check-firmware-pitch.py from Core/Src/main.c. Do not edit. */
#include <stdio.h>
#include <stdint.h>
{defines}
{params}
{decl}
{div_round}
{pitch}
{apply_fn}

/* The formula the above replaced, kept here to prove the default is unchanged. */
static uint8_t pitch_for_xy_legacy(int32_t x, int32_t y, uint8_t *note_out, uint16_t *bend_out)
{{
  int32_t w = x + 23, h = y + 7;
  int32_t step = 5 * w + 3 * h;
  int32_t note = div_round(step * 12, 31);
  int32_t off31 = step * 1200 - note * 100 * 31;
  int32_t bend = 8192 + div_round(off31 * 8192, 4800 * 31);
  if (note < 0 || note > 127 || bend < 0 || bend > 16383) return 0;
  *note_out = (uint8_t)note; *bend_out = (uint16_t)bend; return 1;
}}

static const int LED_POS[{len(led_pos)}][2] = {{ {pos} }};
static const int32_t FIFTHS[] = {{ {fifths} }};
static const int16_t MATS[{len(LAYOUTS)}][4] = {{ {mats} }};
static const int16_t ANCH[{len(LAYOUTS)}][2] = {{ {anch} }};
#define NKEYS  ((int)(sizeof(LED_POS)/sizeof(LED_POS[0])))
#define NFIFTH ((int)(sizeof(FIFTHS)/sizeof(FIFTHS[0])))
#define NBOARD {BOARDS}

static void frame(uint8_t *m, int32_t fifth, const int16_t *mat, const int16_t *a)
{{
  m[0]=fifth&0xff; m[1]=(fifth>>8)&0xff; m[2]=(fifth>>16)&0xff; m[3]=(fifth>>24)&0xff;
  int16_t v[6] = {{ mat[0],mat[1],mat[2],mat[3],a[0],a[1] }};
  for (int i=0;i<6;i++) {{ m[4+i*2]=v[i]&0xff; m[5+i*2]=(v[i]>>8)&0xff; }}
}}

int main(void)
{{
  /* 1. the default must be byte-identical to the formula it replaced */
  int bad = 0;
  for (int b=0;b<NBOARD;b++) for (int k=0;k<NKEYS;k++) {{
    int32_t x = LED_POS[k][0]+5*b, y = LED_POS[k][1]+2*b;
    uint8_t n1,n2; uint16_t b1,b2;
    uint8_t o1 = pitch_for_xy(x,y,&n1,&b1), o2 = pitch_for_xy_legacy(x,y,&n2,&b2);
    if (o1!=o2 || (o1 && (n1!=n2 || b1!=b2))) {{
      bad++;
      fprintf(stderr, "default differs at %ld,%ld: %u/%u vs %u/%u\\n",
              (long)x,(long)y,n1,b1,n2,b2);
    }}
  }}
  printf("DEFAULT_IDENTICAL %d %d\\n", bad==0, NBOARD*NKEYS);

  /* 2. validation must refuse what the companion would never send */
  uint8_t m[PITCH_MSG_LEN];
  const int16_t id[4] = {{1,0,0,1}}, one[4] = {{1,1,1,1}}, big[4] = {{999,0,0,1}};
  const int16_t ok[2] = {{23,7}}, huge[2] = {{9999,7}};
  frame(m, 600000, id, ok);   printf("REJECT low %d\\n",      !pitch_params_apply(m));
  frame(m, 800000, id, ok);   printf("REJECT high %d\\n",     !pitch_params_apply(m));
  frame(m, 696774, one, ok);  printf("REJECT singular %d\\n", !pitch_params_apply(m));
  frame(m, 696774, big, ok);  printf("REJECT matrix %d\\n",   !pitch_params_apply(m));
  frame(m, 696774, id, huge); printf("REJECT anchor %d\\n",   !pitch_params_apply(m));

  /* 3. the full table, for diffing against the companion's */
  for (int fi=0; fi<NFIFTH; fi++) for (int li=0; li<{len(LAYOUTS)}; li++) {{
    frame(m, FIFTHS[fi], MATS[li], ANCH[li]);
    if (!pitch_params_apply(m)) {{ printf("ROW %ld %d rejected\\n", (long)FIFTHS[fi], li); continue; }}
    for (int b=0;b<NBOARD;b++) for (int k=0;k<NKEYS;k++) {{
      int32_t x = LED_POS[k][0]+5*b, y = LED_POS[k][1]+2*b;
      uint8_t note; uint16_t bend;
      if (pitch_for_xy(x,y,&note,&bend))
        printf("ROW %ld %d %ld %ld %u %u\\n", (long)FIFTHS[fi], li, (long)x, (long)y, note, bend);
      else
        printf("ROW %ld %d %ld %ld - -\\n", (long)FIFTHS[fi], li, (long)x, (long)y);
    }}
  }}
  return 0;
}}
"""


JS_MIRROR = """
// The firmware's arithmetic in JS. This is the only copy outside main.c; see the
// comment on midiFor in tuning.ts for why it must not live in src/.
//
// LED_POS arrives in the payload rather than by import, so the two sides cannot
// disagree about which coordinates exist and this file can run from anywhere.
const divRound = (n, d) =>
  n >= 0 ? Math.floor((n + Math.floor(d / 2)) / d) : -Math.floor((-n + Math.floor(d / 2)) / d);
const { fifths, layouts, boards, ledPos } = JSON.parse(process.argv[2]);
const out = [];
for (const f of fifths) {
  for (let li = 0; li < layouts.length; li++) {
    const [[m00, m01, m10, m11], [aw, ah]] = layouts[li];
    for (let b = 0; b < boards; b++) {
      for (const [lx, ly] of ledPos) {
        const x = lx + 5 * b, y = ly + 2 * b;
        const w = m00 * x + m01 * y + aw, h = m10 * x + m11 * y + ah;
        const cm = f * (2 * w - 5 * h) + 1200000 * (3 * h - w);
        const note = divRound(cm, 100000);
        const bend = 8192 + divRound((cm - note * 100000) * 8192, 4800 * 1000);
        const bad = note < 0 || note > 127 || bend < 0 || bend > 16383;
        out.push(`ROW ${f} ${li} ${x} ${y} ` + (bad ? "- -" : `${note} ${bend}`));
      }
    }
  }
}
console.log(out.join("\\n"));
"""


def main() -> int:
    if not shutil.which("clang"):
        sys.exit("clang not found")
    src = MAIN_C.read_text()

    # LED_POS comes from the app, so the two sides cannot disagree about which
    # coordinates exist.
    led_pos = json.loads(
        subprocess.run(
            [
                "node",
                "--import",
                str(HERE / "ts-resolve.mjs"),
                "-e",
                'const {LED_POS} = await import("./src/lib/layout.ts");'
                "console.log(JSON.stringify(LED_POS));",
            ],
            cwd=COMPANION,
            capture_output=True,
            text=True,
            check=True,
        ).stdout
    )

    with tempfile.TemporaryDirectory() as tmp:
        tmpd = pathlib.Path(tmp)
        (tmpd / "harness.c").write_text(build_harness(src, led_pos))
        subprocess.run(
            ["clang", "-O2", "-Wall", "-Wextra", "-Werror", "-o", str(tmpd / "harness"),
             str(tmpd / "harness.c")],
            check=True,
        )
        c_out = subprocess.run([str(tmpd / "harness")], capture_output=True, text=True, check=True)

        (tmpd / "mirror.mjs").write_text(JS_MIRROR)
        payload = json.dumps(
            {"fifths": FIFTHS, "layouts": LAYOUTS, "boards": BOARDS, "ledPos": led_pos}
        )
        js_out = subprocess.run(
            ["node", str(tmpd / "mirror.mjs"), payload],
            capture_output=True,
            text=True,
            check=True,
        )

    failures = 0

    for line in c_out.stdout.splitlines():
        if line.startswith("DEFAULT_IDENTICAL"):
            _, identical, n = line.split()
            if identical == "1":
                print(f"  the 31-EDO default is byte-identical to the old formula ({n} keys)")
            else:
                failures += 1
                print("  FAIL  the default is NOT byte-identical to the old formula")
        elif line.startswith("REJECT"):
            _, what, rejected = line.split()
            if rejected != "1":
                failures += 1
                print(f"  FAIL  a {what} frame was accepted")

    c_rows = [l for l in c_out.stdout.splitlines() if l.startswith("ROW")]
    js_rows = [l for l in js_out.stdout.splitlines() if l.startswith("ROW")]
    if c_rows == js_rows:
        print(f"  firmware arithmetic matches the companion's on all {len(c_rows)} cases")
    else:
        failures += 1
        print(f"  FAIL  {sum(a != b for a, b in zip(c_rows, js_rows))} of {len(c_rows)} differ")
        for a, b in zip(c_rows, js_rows):
            if a != b:
                print(f"          firmware: {a}\n          companion: {b}")
                break

    print("PASS" if failures == 0 else "FAIL")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
