/**
  ******************************************************************************
  * @file    mesh.h
  * @brief   Multi-board topology, event forwarding and colour routing.
  *
  * A tiled grid of Misos behaves as one instrument: the USB-connected board
  * ("master") plays every key in the grid and colour schemes can be painted
  * onto any board in it.
  *
  * Boards tile on the lattice generated by right = (5, 2) and down = (-3, 5).
  * That lattice has determinant 31 -- exactly the key count -- and the board's
  * 31 cells form a complete residue system modulo it, so the shape tiles the
  * plane with no gaps or overlaps. Two things follow, and this layer leans on
  * both: an absolute coordinate uniquely identifies one key in the whole grid
  * (so it serves directly as a key id), and coordinate -> (board, sensor) is
  * unambiguous.
  *
  * Topology is a spanning tree rooted at the master, because a grid contains
  * cycles (any 2x2 block) and a flood would loop. Events travel up to the
  * parent only, so each arrives exactly once; colours travel down to children
  * only, which is acyclic.
  *
  * The TOP port has no USART (only three full-duplex pairs are bonded out on
  * UFQFPN32) and runs on the software UART in softuart.c. This layer is
  * written general over all four ports and does not distinguish it.
  ******************************************************************************
  */

#ifndef __MESH_H
#define __MESH_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "link.h"

#define MESH_MAX_BOARDS   16
#define MESH_SENSORS      31   /* must match NUM_SENSORS; checked in main.c */
#define MESH_RGB_BYTES    (MESH_SENSORS * 3)   /* RGB, LED-chain order */

void mesh_init(void);
void mesh_tick(uint32_t tick);

/* Every local key event goes through these, in ABSOLUTE coordinates. On the
 * master they are emitted straight away; elsewhere they are sent to the parent.
 * keys_process() does not need to know which it is. */
void mesh_key_down(uint8_t sensor, int16_t x, int16_t y, uint8_t vel, uint32_t dt_us);
void mesh_key_up(uint8_t sensor, int16_t x, int16_t y);

/* This board's discovered origin. Local sensor coordinates are added to it to
 * get absolute ones; the master is always (0, 0). */
int16_t mesh_offset_x(void);
int16_t mesh_offset_y(void);
uint8_t mesh_is_master(void);

/* Colour frame for the board whose origin is (x, y): applied here if that is
 * us, otherwise routed down the tree. 93 bytes, RGB in LED-chain order. */
void mesh_set_colors(int16_t x, int16_t y, const uint8_t *rgb);

/* 'T' command: one line per port and per known board, plus a counters line. */
void mesh_dump(void);

/* --- Provided by main.c ---------------------------------------------------
 * Kept as a narrow seam so mesh.c needs nothing else from the application. */

void     Miso_EmitKeyDown(uint8_t sensor, int16_t x, int16_t y, uint8_t vel, uint32_t dt_us);
void     Miso_EmitKeyUp(uint8_t sensor, int16_t x, int16_t y);
void     Miso_ApplyColors(const uint8_t *rgb);
void     Miso_SensorCoord(uint8_t sensor, int8_t *x, int8_t *y);
uint32_t Miso_LocalHeldMask(void);
void     Miso_SendText(const char *s);

#ifdef __cplusplus
}
#endif

#endif /* __MESH_H */
