// The grid: which boards exist, where they sit, and the cells they contribute.
//
// Boards tile on the lattice generated by right = (5,2) and down = (-3,5).
// That lattice has determinant 31 — exactly the key count — and the board's 31
// cells form a complete residue system modulo it, so the shape tiles the plane
// with no gaps or overlaps. Two consequences this module relies on: an absolute
// coordinate identifies exactly one key in the whole grid (so "x,y" is a usable
// key id), and coordinate -> (board, led) is unambiguous.
//
// Topology comes from the firmware's `T` command, whose output looks like:
//
//   MESH self=00440034 off=0,0 depth=0 master=1 root=00440034
//   MESH port=right  role=child  peer=00190037 geom=ok
//   MESH board=00440034 off=0,0 held=00000000 age=91
//   MESH stat missed_down=0 fixed_up=0 lost_release=0 geom_err=0 multi_master=0
//
// The `stat` line is always last, so it doubles as the commit point for a
// snapshot — a half-parsed grid is never shown.

import { LED_POS, SENSOR_FOR_LED, NUM_KEYS, cellKey } from "./layout";

export { cellKey };

/** Neighbour offsets, matching dir_vec[] in the firmware's mesh.c. */
export const RIGHT: readonly [number, number] = [5, 2];
export const DOWN: readonly [number, number] = [-3, 5];

export interface Board {
  uid: string;
  ox: number;
  oy: number;
  /** 31-bit held mask by sensor index, as the firmware reports it. */
  held: number;
  /** Milliseconds since the master last heard from this board. */
  ageMs: number;
  self: boolean;
}

export interface PortInfo {
  name: string;
  role: string;
  peer: string;
  geomOk: boolean;
}

export interface MeshStats {
  missedDown: number;
  fixedUp: number;
  lostRelease: number;
  geomErr: number;
  multiMaster: number;
}

/** A single key somewhere in the grid. */
export interface Cell {
  /** "x,y" — unique across the whole grid, and the colour-map key. */
  key: string;
  x: number;
  y: number;
  board: Board;
  led: number;
  sensor: number;
}

const SOLO: Board = { uid: "—", ox: 0, oy: 0, held: 0, ageMs: 0, self: true };

export const mesh = $state({
  /** Never empty: falls back to a single board at the origin. */
  boards: [SOLO] as Board[],
  selfUid: "",
  depth: 0,
  isMaster: true,
  /** True once a MESH line has ever been parsed — i.e. the firmware speaks `T`. */
  seen: false,
  ports: [] as PortInfo[],
  stats: { missedDown: 0, fixedUp: 0, lostRelease: 0, geomErr: 0, multiMaster: 0 } as MeshStats,
});

// A `T` response arrives as a burst of lines; accumulate and commit on `stat`.
let pendingBoards: Board[] = [];
let pendingPorts: PortInfo[] = [];
let pendingSelf = "";
let pendingDepth = 0;
let pendingMaster = true;

const num = (s: string | undefined, base = 10) => (s === undefined ? 0 : parseInt(s, base));

/**
 * Consume one status line. Returns true if it was a MESH line (and therefore
 * should not be treated as anything else).
 */
export function parseMeshLine(line: string): boolean {
  if (!line.startsWith("MESH ")) return false;

  const self = line.match(/^MESH self=(\w+) off=(-?\d+),(-?\d+) depth=(-?\d+) master=(\d)/);
  if (self) {
    pendingBoards = [];
    pendingPorts = [];
    pendingSelf = self[1];
    pendingDepth = num(self[4]);
    pendingMaster = self[5] === "1";
    return true;
  }

  const port = line.match(/^MESH port=(\w+)\s+role=(\w+)\s+peer=(\w+) geom=(\w+)/);
  if (port) {
    pendingPorts.push({ name: port[1], role: port[2], peer: port[3], geomOk: port[4] === "ok" });
    return true;
  }

  const board = line.match(/^MESH board=(\w+) off=(-?\d+),(-?\d+) held=([0-9a-fA-F]+) age=(\d+)/);
  if (board) {
    pendingBoards.push({
      uid: board[1],
      ox: num(board[2]),
      oy: num(board[3]),
      held: num(board[4], 16),
      ageMs: num(board[5]),
      self: board[1] === pendingSelf,
    });
    return true;
  }

  const stat = line.match(
    /^MESH stat missed_down=(\d+) fixed_up=(\d+)(?: lost_release=(\d+))? geom_err=(\d+) multi_master=(\d+)/,
  );
  if (stat) {
    // Commit the snapshot. Sort so rendering order is stable as boards come
    // and go, rather than following discovery order.
    mesh.boards = pendingBoards.length
      ? [...pendingBoards].sort((a, b) => a.oy - b.oy || a.ox - b.ox)
      : [SOLO];
    mesh.ports = pendingPorts;
    mesh.selfUid = pendingSelf;
    mesh.depth = pendingDepth;
    mesh.isMaster = pendingMaster;
    mesh.stats = {
      missedDown: num(stat[1]),
      fixedUp: num(stat[2]),
      lostRelease: num(stat[3]),
      geomErr: num(stat[4]),
      multiMaster: num(stat[5]),
    };
    mesh.seen = true;
    return true;
  }

  return true; // an unrecognised MESH line is still ours; don't log it as junk
}

/** Reset to the solo fallback (on disconnect, or when simulating). */
export function resetMesh(): void {
  mesh.boards = [SOLO];
  mesh.ports = [];
  mesh.seen = false;
  mesh.selfUid = "";
  mesh.depth = 0;
  mesh.isMaster = true;
  mesh.stats = { missedDown: 0, fixedUp: 0, lostRelease: 0, geomErr: 0, multiMaster: 0 };
}


/** Every key in the grid, in board order then LED-chain order. */
export function gridCells(): Cell[] {
  const out: Cell[] = [];
  for (const b of mesh.boards) {
    for (let led = 0; led < NUM_KEYS; led++) {
      const [lx, ly] = LED_POS[led];
      const x = lx + b.ox;
      const y = ly + b.oy;
      out.push({ key: cellKey(x, y), x, y, board: b, led, sensor: SENSOR_FOR_LED[led] });
    }
  }
  return out;
}

/** Which board owns an absolute coordinate, if any. */
export function boardForCoord(x: number, y: number): Board | null {
  for (const b of mesh.boards) {
    const lx = x - b.ox;
    const ly = y - b.oy;
    if (LED_POS.some(([px, py]) => px === lx && py === ly)) return b;
  }
  return null;
}
